const http = require('http');

const PORT = process.env.PORT || 3000;
const VERSION = process.env.VERSION || '1.0.0';

const landingHtml = [
'<!DOCTYPE html>',
'<html lang="en">',
'<head>',
'  <meta charset="UTF-8">',
'  <meta name="viewport" content="width=device-width, initial-scale=1.0">',
'  <title>Getouch — Intelligent Engagement Platform</title>',
'  <style>',
'    *, *::before, *::after { margin: 0; padding: 0; box-sizing: border-box; }',
'    :root {',
'      --bg: #0a0a0b; --surface: #111113; --border: #1e1e22;',
'      --text: #e4e4e7; --text-muted: #71717a; --accent: #6366f1;',
'      --accent-glow: rgba(99, 102, 241, 0.15); --green: #22c55e;',
'    }',
'    body {',
'      font-family: -apple-system, BlinkMacSystemFont, "Inter", "Segoe UI", sans-serif;',
'      background: var(--bg); color: var(--text); min-height: 100vh;',
'      overflow-x: hidden; -webkit-font-smoothing: antialiased;',
'    }',
'    .bg-mesh {',
'      position: fixed; inset: 0; z-index: 0;',
'      background: radial-gradient(ellipse 600px 400px at 20% 20%, rgba(99,102,241,0.06), transparent),',
'        radial-gradient(ellipse 500px 300px at 80% 80%, rgba(139,92,246,0.04), transparent);',
'    }',
'    .container { position: relative; z-index: 1; max-width: 1200px; margin: 0 auto; padding: 0 24px; }',
'    nav { display: flex; align-items: center; justify-content: space-between; padding: 20px 0; border-bottom: 1px solid var(--border); }',
'    .logo { font-size: 1.25rem; font-weight: 700; letter-spacing: -0.02em; color: var(--text); }',
'    .logo span { color: var(--accent); }',
'    .nav-links { display: flex; gap: 32px; list-style: none; }',
'    .nav-links a { color: var(--text-muted); text-decoration: none; font-size: 0.875rem; font-weight: 500; transition: color 0.2s; }',
'    .nav-links a:hover { color: var(--text); }',
'    .status-badge { display: inline-flex; align-items: center; gap: 6px; padding: 6px 14px; border-radius: 999px; background: rgba(34,197,94,0.1); border: 1px solid rgba(34,197,94,0.2); font-size: 0.75rem; color: var(--green); font-weight: 500; }',
'    .status-dot { width: 6px; height: 6px; border-radius: 50%; background: var(--green); animation: pulse 2s ease-in-out infinite; }',
'    @keyframes pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.4; } }',
'    .hero { padding: 120px 0 80px; text-align: center; }',
'    .hero-eyebrow { display: inline-block; padding: 6px 16px; border-radius: 999px; background: var(--accent-glow); border: 1px solid rgba(99,102,241,0.2); color: var(--accent); font-size: 0.8rem; font-weight: 600; letter-spacing: 0.05em; text-transform: uppercase; margin-bottom: 24px; }',
'    .hero h1 { font-size: clamp(2.5rem, 6vw, 4.5rem); font-weight: 800; letter-spacing: -0.03em; line-height: 1.1; margin-bottom: 20px; }',
'    .hero h1 .gradient-text { background: linear-gradient(135deg, var(--accent), #a78bfa, #ec4899); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; }',
'    .hero p { max-width: 560px; margin: 0 auto 40px; color: var(--text-muted); font-size: 1.125rem; line-height: 1.7; }',
'    .hero-actions { display: flex; gap: 12px; justify-content: center; flex-wrap: wrap; }',
'    .btn { display: inline-flex; align-items: center; gap: 8px; padding: 12px 28px; border-radius: 10px; font-size: 0.9rem; font-weight: 600; text-decoration: none; transition: all 0.2s; cursor: pointer; border: none; }',
'    .btn-primary { background: var(--accent); color: white; box-shadow: 0 0 24px rgba(99,102,241,0.3); }',
'    .btn-primary:hover { background: #818cf8; box-shadow: 0 0 32px rgba(99,102,241,0.4); transform: translateY(-1px); }',
'    .btn-ghost { background: transparent; color: var(--text-muted); border: 1px solid var(--border); }',
'    .btn-ghost:hover { color: var(--text); border-color: #2e2e34; background: var(--surface); }',
'    .features { padding: 80px 0; }',
'    .features-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 20px; }',
'    .feature-card { padding: 32px; background: var(--surface); border: 1px solid var(--border); border-radius: 16px; transition: all 0.3s; }',
'    .feature-card:hover { border-color: rgba(99,102,241,0.3); transform: translateY(-2px); box-shadow: 0 8px 32px rgba(0,0,0,0.3); }',
'    .feature-icon { width: 44px; height: 44px; border-radius: 12px; background: var(--accent-glow); display: flex; align-items: center; justify-content: center; margin-bottom: 20px; font-size: 1.25rem; }',
'    .feature-card h3 { font-size: 1.05rem; font-weight: 700; margin-bottom: 8px; letter-spacing: -0.01em; }',
'    .feature-card p { color: var(--text-muted); font-size: 0.875rem; line-height: 1.6; }',
'    .stats { padding: 60px 0; display: flex; justify-content: center; gap: 60px; flex-wrap: wrap; }',
'    .stat { text-align: center; }',
'    .stat-value { font-size: 2.5rem; font-weight: 800; letter-spacing: -0.03em; background: linear-gradient(135deg, var(--text), var(--text-muted)); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }',
'    .stat-label { font-size: 0.8rem; color: var(--text-muted); text-transform: uppercase; letter-spacing: 0.08em; margin-top: 4px; }',
'    footer { padding: 40px 0; border-top: 1px solid var(--border); text-align: center; }',
'    footer p { color: var(--text-muted); font-size: 0.8rem; }',
'    footer a { color: var(--accent); text-decoration: none; }',
'    @media (max-width: 640px) { .nav-links { display: none; } .hero { padding: 80px 0 60px; } .stats { gap: 40px; } }',
'  </style>',
'</head>',
'<body>',
'  <div class="bg-mesh"></div>',
'  <div class="container">',
'    <nav>',
'      <div class="logo">ge<span>touch</span></div>',
'      <ul class="nav-links">',
'        <li><a href="#features">Features</a></li>',
'        <li><a href="https://api.getouch.co/health">API</a></li>',
'        <li><a href="https://bot.getouch.co/health">Bot</a></li>',
'      </ul>',
'      <div class="status-badge"><div class="status-dot"></div>All Systems Operational</div>',
'    </nav>',
'    <section class="hero">',
'      <div class="hero-eyebrow">AI-Powered Platform</div>',
'      <h1>Engage smarter.<br><span class="gradient-text">Connect deeper.</span></h1>',
'      <p>Getouch is an intelligent engagement platform powered by on-premises AI. Built for speed, privacy, and scale — running on your own infrastructure.</p>',
'      <div class="hero-actions">',
'        <a href="https://api.getouch.co/health" class="btn btn-primary">',
'          <svg width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M5 12h14M12 5l7 7-7 7"/></svg>Explore API</a>',
'        <a href="https://bot.getouch.co/health" class="btn btn-ghost">',
'          <svg width="16" height="16" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><circle cx="12" cy="12" r="10"/><path d="M8 14s1.5 2 4 2 4-2 4-2"/><line x1="9" y1="9" x2="9.01" y2="9"/><line x1="15" y1="9" x2="15.01" y2="9"/></svg>Try Bot</a>',
'      </div>',
'    </section>',
'    <section class="features" id="features">',
'      <div class="features-grid">',
'        <div class="feature-card"><div class="feature-icon">&#129302;</div><h3>AI Chat Bot</h3><p>Conversational AI powered by Qwen2.5 7B running on local GPU. Fast, private, and fully under your control.</p></div>',
'        <div class="feature-card"><div class="feature-icon">&#128172;</div><h3>WhatsApp Integration</h3><p>Connect with customers on WhatsApp via Baileys. Automated responses, webhooks, and seamless handoff.</p></div>',
'        <div class="feature-card"><div class="feature-icon">&#9889;</div><h3>REST API</h3><p>Clean, documented API endpoints for programmatic access to all platform features. Built with Node.js.</p></div>',
'        <div class="feature-card"><div class="feature-icon">&#128274;</div><h3>Zero Trust Security</h3><p>Cloudflare Tunnel ingress with no open ports. Admin access protected by Cloudflare Access policies.</p></div>',
'        <div class="feature-card"><div class="feature-icon">&#128421;</div><h3>GPU Accelerated</h3><p>NVIDIA RTX GPU powering on-premises AI inference. Sub-second response times for all LLM operations.</p></div>',
'        <div class="feature-card"><div class="feature-icon">&#128200;</div><h3>Full Observability</h3><p>Prometheus metrics, Grafana dashboards, and automated backups. Know exactly what is happening.</p></div>',
'      </div>',
'    </section>',
'    <section class="stats">',
'      <div class="stat"><div class="stat-value">4</div><div class="stat-label">Microservices</div></div>',
'      <div class="stat"><div class="stat-value">&lt;1s</div><div class="stat-label">AI Response</div></div>',
'      <div class="stat"><div class="stat-value">0</div><div class="stat-label">Open Ports</div></div>',
'      <div class="stat"><div class="stat-value">24/7</div><div class="stat-label">Monitoring</div></div>',
'    </section>',
'    <footer><p>&copy; 2026 <a href="https://getouch.co">getouch.co</a> — Powered by open-source AI on home infrastructure</p></footer>',
'  </div>',
'</body>',
'</html>'
].join('\n');

const adminHtml = [
'<!DOCTYPE html>',
'<html lang="en">',
'<head>',
'  <meta charset="UTF-8">',
'  <meta name="viewport" content="width=device-width, initial-scale=1.0">',
'  <title>Getouch Admin</title>',
'  <style>',
'    *, *::before, *::after { margin: 0; padding: 0; box-sizing: border-box; }',
'    :root { --bg: #0a0a0b; --surface: #111113; --border: #1e1e22; --text: #e4e4e7; --text-muted: #71717a; --accent: #6366f1; --green: #22c55e; --red: #ef4444; --yellow: #eab308; }',
'    body { font-family: -apple-system, BlinkMacSystemFont, "Inter", "Segoe UI", sans-serif; background: var(--bg); color: var(--text); min-height: 100vh; -webkit-font-smoothing: antialiased; }',
'    .admin-container { max-width: 960px; margin: 0 auto; padding: 40px 24px; }',
'    h1 { font-size: 1.5rem; font-weight: 700; margin-bottom: 8px; letter-spacing: -0.02em; }',
'    .subtitle { color: var(--text-muted); margin-bottom: 32px; font-size: 0.9rem; }',
'    .card { background: var(--surface); border: 1px solid var(--border); border-radius: 12px; padding: 24px; margin-bottom: 16px; }',
'    .card h2 { font-size: 1rem; font-weight: 600; margin-bottom: 16px; }',
'    .service-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 12px; }',
'    .service-item { display: flex; align-items: center; gap: 10px; padding: 12px 16px; background: var(--bg); border: 1px solid var(--border); border-radius: 8px; }',
'    .service-dot { width: 8px; height: 8px; border-radius: 50%; }',
'    .service-dot.checking { background: var(--yellow); animation: pulse 1s infinite; }',
'    .service-dot.up { background: var(--green); }',
'    .service-dot.down { background: var(--red); }',
'    .service-name { font-size: 0.85rem; font-weight: 600; }',
'    .service-url { font-size: 0.7rem; color: var(--text-muted); }',
'    .service-latency { margin-left: auto; font-size: 0.7rem; color: var(--text-muted); }',
'    .log-section pre { background: var(--bg); border: 1px solid var(--border); border-radius: 8px; padding: 16px; font-size: 0.75rem; color: var(--text-muted); overflow-x: auto; line-height: 1.6; font-family: "SF Mono", monospace; }',
'    @keyframes pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.4; } }',
'  </style>',
'</head>',
'<body>',
'  <div class="admin-container">',
'    <h1>Getouch Admin</h1>',
'    <p class="subtitle">Internal dashboard — protected by Cloudflare Access</p>',
'    <div class="card">',
'      <h2>Service Health</h2>',
'      <div class="service-grid" id="services"></div>',
'    </div>',
'    <div class="card">',
'      <h2>Quick Links</h2>',
'      <div class="service-grid">',
'        <a href="http://100.103.248.15:5050" style="text-decoration:none" class="service-item"><span class="service-name" style="color:var(--accent)">pgAdmin</span><span class="service-url">:5050 (Tailscale)</span></a>',
'        <a href="http://100.103.248.15:3001" style="text-decoration:none" class="service-item"><span class="service-name" style="color:var(--accent)">Grafana</span><span class="service-url">:3001 (Tailscale)</span></a>',
'      </div>',
'    </div>',
'    <div class="card log-section">',
'      <h3>Log Commands</h3>',
'      <pre>ssh deploy@100.103.248.15',
'cd /opt/getouch/compose',
'docker compose logs -f caddy --tail 100',
'docker compose -f docker-compose.apps.yml logs -f --tail 100</pre>',
'    </div>',
'  </div>',
'  <script>',
'    var services = [',
'      { name: "Landing", url: "/health" },',
'      { name: "Bot", url: "https://bot.getouch.co/health" },',
'      { name: "WhatsApp", url: "https://wa.getouch.co/health" },',
'      { name: "API", url: "https://api.getouch.co/health" }',
'    ];',
'    var grid = document.getElementById("services");',
'    services.forEach(function(s) {',
'      var el = document.createElement("div");',
'      el.className = "service-item";',
'      var dot = document.createElement("div");',
'      dot.className = "service-dot checking";',
'      dot.id = "dot-" + s.name;',
'      var info = document.createElement("div");',
'      var nm = document.createElement("div");',
'      nm.className = "service-name"; nm.textContent = s.name;',
'      var ur = document.createElement("div");',
'      ur.className = "service-url"; ur.textContent = s.url;',
'      info.appendChild(nm); info.appendChild(ur);',
'      var lat = document.createElement("div");',
'      lat.className = "service-latency"; lat.id = "lat-" + s.name; lat.textContent = "...";',
'      el.appendChild(dot); el.appendChild(info); el.appendChild(lat);',
'      grid.appendChild(el);',
'      var t0 = performance.now();',
'      fetch(s.url).then(function(r) { return r.json(); }).then(function(d) {',
'        var ms = Math.round(performance.now() - t0);',
'        document.getElementById("dot-" + s.name).className = "service-dot " + (d.status === "ok" ? "up" : "down");',
'        document.getElementById("lat-" + s.name).textContent = ms + "ms";',
'      }).catch(function() {',
'        document.getElementById("dot-" + s.name).className = "service-dot down";',
'        document.getElementById("lat-" + s.name).textContent = "err";',
'      });',
'    });',
'  </script>',
'</body>',
'</html>'
].join('\n');

const server = http.createServer(function(req, res) {
  if (req.url === '/health') {
    res.writeHead(200, { 'Content-Type': 'application/json' });
    return res.end(JSON.stringify({
      service: 'landing',
      status: 'ok',
      version: VERSION,
      timestamp: new Date().toISOString()
    }));
  }

  if (req.url === '/admin') {
    res.writeHead(302, { Location: '/admin/' });
    return res.end();
  }

  if (req.url && req.url.indexOf('/admin/') === 0) {
    res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
    return res.end(adminHtml);
  }

  res.writeHead(200, { 'Content-Type': 'text/html; charset=utf-8' });
  res.end(landingHtml);
});

server.listen(PORT, '0.0.0.0', function() {
  console.log('[landing] listening on port ' + PORT);
});
